### PR TITLE
fix: input border was displayed incorrectly

### LINKED ISSUE #40: [COMPONENT] Inputs Focus fix on Safari
We already have some code from the Hackathon so please check and finalize the Inputs design incorporation in code
#17 
#19 

Notes

-[Figma Design](https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?node-id=1454%3A934&t=OJ1WWHoZRfBoVcVk-11)

### PR DESCRIPTION
**Pull request by DawidHaratyk**
# Overview:

closes #40

### Short description and worth mentioning decision made.

- Fixed border on safari
- The icons now are out of context (I've positioned them absolutely)

### CODE REVIEW

File: packages/selleo-design-core/src/SearchInput.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ export function SearchInput({ label }: SearchInputProps) {
   });
 
   const inputClasses = cx(
-    'w-full h-[56px] pr-[48px] pl-2 bg-white text-neutral-600 hover:placeholder:text-neutral-600 focus:placeholder:text-neutral-600 border-[1px] rounded-[4px] border-neutral-200 outline-brand-primary-500 hover:border-neutral-300 peer text-xs',
+    'w-full h-[56px] pr-[48px] pl-2 bg-white outline-none text-neutral-600 hover:placeholder:text-neutral-600 focus:placeholder:text-neutral-600 border-[1px] rounded-[4px] border-neutral-200 focus:border-brand-primary-500 hover:border-neutral-300 peer text-xs',
```
Comment (k1eu) [inline packages/selleo-design-core/src/SearchInput.tsx:16]: will focus-visble work instead of focus? That way we won't trigger it by clicking only by tabbing

**Review by k1eu — CHANGES_REQUESTED** [review]

File: packages/selleo-design-core/src/SearchInput.tsx (hunk 1 above)
Comment (DawidHaratyk) [reply packages/selleo-design-core/src/SearchInput.tsx]: Yes, it works
